---
title: Hello Echo Graph
nodes:
  hello:
    runtime: deno
    git_url: https://github.com/julian-computes/sonata.git
    workflow_path: example-workflows/hello-world
  echo:
    runtime: deno
    git_url: https://github.com/julian-computes/sonata.git
    workflow_path: example-workflows/echo
---

graph TD
  hello --> echo --> echo
